### ISSUE TITLE
Create the view to add request, list requests, upload result

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/eln-couch#25]
## View to create request

Create a view that allows to submit a request for analysis based on a domain (could be specified in the url as a parameter).

For example I would like that an end-user based on a list of domain like ch.epfl.isic will see the list of possible either set of analysis of individual analysis and is able to submit an analysis.

A request HAS to be based on a sample. This means that even if we want to create a request from a splash screen there should be first a sample Code, / batch Code in order to create the sample and once the sample has been created the request could be associated to it (Array of uuid of sample ?).
## View to list requests

There should be a view that list the current request based on a "domain" (ch.epfl.isic.nmr). This view may be quite specific. In some case it would download a file to start automatically an experiment (Bruker topspin). In other cases it would just allow directly to upload the result (copy paste a mass spectrum or drag and drop an image). We should give the possibility to modify the status of the request.
## What about the protection ?

I think that each type of analysis should be associated with a username name (or generic username) and when a user request an analysis he would give the modification right to the responsible of the laboratory.

**Comment by lpatiny** [comment]
@andcastillo @jwist

**Comment by jwist** [comment]
Hi!
We are trying to work on the request with AMC

and we have some observations….

In the view “Analysis services" the configuration should refer to the configuration of the instrument. For example the same spectrometer can work with a BBO probe or with a BBI probe. In that case we have two choices 1) to define a new service for each configuration 2) to have the possibility to define the configuration.

The problem is that configurations might be “active” or “inactive”, because you maybe not want to accept jobs of a configuration during a particular week so maybe it is best to define a new service for each configuration, and to have the possibility to define “service availability” and to have a longer description of the service where it is possible to define the configuration of the machine with greater details.

It is important to be able to flag the service as "active" or "inactive" because you might not want to delete the configuration of a service, but don't want people to submit request. You also would like people to "see" it or not, even if active or inactive, so there should be a "publish" o "hide" flag, as well.

In that case, I would also suggest to change the name “configuration” for “experiment” in the current view

**Comment by jwist** [comment]
Following the discussion...

it is also important to consider long descriptions fields where we can describe the choices. For example, an experiment "1H" could have a description where we can put some explication (markdown). The same for instrument, it would be nice to be able to add a long description and maybe event put an image of the machine.

**Comment by lpatiny** [comment]
Concerning picture we could make them in-line in a rich-text-editor but in the eln-reaction there is an aexample of upload files and insert directly the link in the rich-text-editor. Maybe we could reuse this approach here.

**Comment by targos** [comment]
I made the following changes to the Analysis services view:
- Add an "active" flag to the instruments (default: true)
- Add a "hidden" flag to the instruments (default: false)
- Changed "configurations" to "experiments"
- Add a description field for instruments and experiments. It is editable with a rich-text editor below the table.

Please give it a try but make sure you are at least on the version v2.52.0 of the visualizer.
~~Also do not use the "Analysis sets" view. I have not updated it yet.~~

**Comment by targos** [comment]
Update: "Analysis sets" is ready

**Comment by jwist** [comment]
- in the form that allows to submit request, it would be nice to have a flag "default" that allows to set the default value
- it would be nice to be able to chose from a list
